---
title: "Research projects"
output: html_document
---

I can supervise undergraduate and Masters by coursework student research projects under programmes by the Department of Biological Sciences at the National University of Singapore. The majority of research opportunities with me will be tied to my work coordinating NParks’ Tropical Forest Ecology Research programme, and especially contributing to the anchor projects on the programme, such as the Long Term Forest Ecological Monitoring (LTFEM) project (see [Er et al. (2023)](/publications.html#ErEtAl_2023)).

Prospective students must be interested in the projects on offer and be willing to work very hard. I offer projects with research questions that I think are meaningful enough to have a chance at publication in a scientific journal, but this is only possible if data quality is sufficiently high, which very much depends on the student carrying out the study. On my part, a lot of time and effort goes into working with the student to develop a robust study design and coaching on how to make sense of data and communicate the work; on the part of the student, the data collection must be meticulous and the sample size must be sufficient. In return, the student will witness (the pains of) science-in-action at first hand and may eventually have the satisfaction of seeing his or her results published (see my track record).

I also require the student to be receptive to criticism.

Feel free to approach any of my former students to find out what to expect from me. If you think you might be able to take it and possess the requisites, please get in touch to arrange a face-to-face chat. However, meeting up does not mean acceptance.

## 1. Comparing tree demographic rates between native-dominated and exotic-dominated forests in Singapore

This project will follow up with previous censuses of stems >/= 5 cm DBH ('trees') in 20 x 20 m plots, stems 1 – 5 cm DBH ('saplings') in 10 x 10 m sub-plots in one corner of these plots, and seedlings >/= 20-cm height in four 1 x 1 m quadrats in each plot. The plots are distributed between the native-dominated forests of the Central Catchment Nature Reserve (33 plots; trees censused in 2022, saplings censused in 2024) and the exotic-dominated forests of four parks: Bukit Batok Nature Park, Bukit Batok Town Park, Thomson Nature Park, Windsor Nature Park (total of 20 plots; trees censused in 2023, saplings censused in 2025). From a new census of these plots, growth, mortality, and recruitment rates of trees in these plots will be compared.

## 2. Tree demographic rates during the thinning phase of forest succession

This project will undertake a re-survey of the 'Mandai storm forest’ plots. See [Ooi et al. (2026)](/publications.html#OoiEtAl_2025) and [Lai et al. (2022)](/publications.html#HughTanSpecial_LaiEtAl) for more information on these plots. In brief, there are 40 plots measuring 10 x 10 m north and south of Mandai road that were censused annually from 2011--2015 and then once in 2023. A previous student re-censused saplings (1 – 5 cm DBH) in 2025 and compared mortality, growth, and recruitment rates between 2023--2025 versus the earlier years. This new re-census will once again compare these demographic rates but of all stems >/= 1 cm DBH.

_These projects (1) and (2) are suitable as either Final Year Projects (i.e., LSM4288E) under the Life Sciences major or Bachelor of Environmental Studies, or a Masters in Biodiversity Conservation and Sustainability Research Project (i.e., BL5199)._

## 3. Monitoring the effects of non-native oil palm removal and understorey enhancement planting as a forest restoration action

This project will re-survey treatment-control pairs of plots where non-native oil palm (_Elaeis guineensis_) were removed in treatment plots and in-planted with native tree saplings.

_This project (3) is suitable as a UROPS project._