---
title: "About me"
output: html_document
---

I am a [forest ecologist at the Singapore Botanic Gardens](https://www.nparks.gov.sg/sbg/research/research-staff/dr-chong-kwek-yan) of the National Parks Board. I am also [adjunct faculty at the Department of Biological Sciences](https://www.dbs.nus.edu.sg/staffs/chong-kwek-yan/?cid=110) at the National University of Singapore (NUS) where I obtained my PhD with a thesis on the effects of greenery on urban biodiversity, and also my Honours degree with a project compiling the total vascular plant flora of Singapore. My previous postdoctoral stints include an NUS Overseas Postdoctoral Fellowship hosted at the Centre of Excellence for Environmental Decisions, Centre for Biodiversity and Conservation Science, University of Queensland.

My research interests are in vegetation ecology, urban ecology, and invasion ecology. I am most proud of the work that I have accomplished in partnership with the students that I mentor/supervise; much of my time and effort goes into making them worthy of making it through scientific peer-review (see my [track record](/past_students.html)).

Other Profiles: [Google Scholar](https://scholar.google.com.sg/citations?user=0LPZNDcAAAAJ), [ResearchGate](https://www.researchgate.net/profile/Kwek-Yan-Chong), [ResearcherID](https://www.webofscience.com/wos/author/record/126371), [ORCID](https://orcid.org/0000-0003-4754-8957), [Scopus](https://www.scopus.com/authid/detail.uri?authorId=36080482100), [GitHub](https://github.com/kwekings)
