---
title: "Publications"
output:
    html_document:
        toc: TRUE
        toc_float: TRUE
---

# A. Peer-reviewed articles in ISI-listed journals
\*I am the corresponding author

<!---
* Song, X.P., E.Y.W. Tan, R.S.K. Lee, H.J. Sim, J.K.H. Nai, J.Y. Chan, S.M.X. Hung, S.H. Ng, E.S.C. Goh, C.Y.T. Tan, L. Cai, Y.K. Chua, A. Xu, D.C.J. Yeo, H.T.W. Tan, **K.Y. Chong**. Conserving urban biodiversity: A predictive approach to monitor and plan for future development scenarios.
Edwards, P., D. Zuzana, **K.Y. Chong**, S.C. Chua, H.R. Lai, R.A.T. Leong, J.D. Moore, D. Richards, M. van Breugel, L.S. Wijedasa, A.T.K. Yee. (in preparation) Comparison of plant functional traits across diverse tree cover types in a tropical city.
* **Chong, K.Y.**, W.Q. Ng, X.Y. Ng, R.C.J. Lim, C.K. Yeo, D. Austin, A.T.K. Yee, X. Giam, S. Teo, J.W. Wang, H.T.W. Tan. (in preparation) Resource provision for birds and butterflies by native and non-native plantings in tropical urban parks.
Choong, M.F., **K.Y. Chong**, K.Y. Soon, S. Yuan, H.T.W. Tan. (in preparation) Comparative performance of an extensive green roof system using four growing media and five plant species.
**Chong, K.Y.**, R. Chong, N.E.B. Rahman, L.W.A. Tan, Q.Y. Ho, Y.Y. Ting, H.R. Lai, Z. Chiam, W.N. Lam, P.J. Chan, K.N. Mohamed Ramdzan, J.S.H. Lim, V.S.L. Lee, J. Liu, C.T.T. Nguyen, D.E. Kim, M. Liew, C.L. Lau, A.D. Ziegler, S.J. Ramchunder, S.-Y. Liong, H. Ibrahim, Y. Cai (in preparation) Teal carbon in non-peat tropical freshwater swamp forest.
* Lee, R.S.K., S.M.X. Hung, C.Y.T. Tan, J.Y. Chan, D.C.J. Yeo, H.T.W. Tan, **K.Y. Chong**. (in review) Learning through time: Longitudinal study validated predictions on urban bird and butterfly communities and examined mechanisms behind biotic homogenization. Landscape and Urban Planning.
--->
1. Lai, H.R., **K.Y. Chong**, M.Q.Y. Wong, H.T.W. Tan, D.C.J. Yeo. (2025) Leaf-litter depth, not canopy openness, mediates the occurrence of an invasive shrub from the forest edge to interior. Biotropica 57: [e70002](https://onlinelibrary.wiley.com/doi/full/10.1111/btp.70002).
<a name="LamEtAl_2024"></a>
1. Ho, B.-C., E.J.J. Chia, **K.Y. Chong**, J.S.Y. Tan, W.X. Tan, S. Lai, T.Y.S. Choo, P.Y. Tan, K.B.H. Er. (2024) Changes in tropical leafing behaviour with climate change over nine decades: A case study from the Singapore Botanic Gardens. Plants People Planet 6: [1469–1479](https://nph.onlinelibrary.wiley.com/doi/full/10.1002/ppp3.10547).
1. \*Lam, W.N., J. Huang, A.H.T. Tay, H.J. Sim, P.J. Chan, K.E. Lim, M. Lei, A.N.A. Aritsara, R. Chong, Y.Y. Ting, N.E. Rahman, T.M. Sloey, M. van Breugel, K.-F. Cao, A.K.S. Wee, **K.Y. Chong**. (2024) Leaf and twig traits predict habitat adaptation and demographic strategies in tropical freshwater swamp forest tree species. New Phytologist 243: [881–893](https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/nph.19876). [[pdf](https://www.dropbox.com/scl/fi/uitlz6lix4gaq2848jj4h/Lam-et-al-2024-Leaf-and-twig-traits-predict-habitat-adaptation-and-demographic-strategies-in-tropical.pdf?rlkey=cr3iiybb3tid78lmqx3e9yscs&dl=0)]
1. Neo, L., **K.Y. Chong**, S. Lindsay, D.J. Middleton, P.Y. Tan, K.B.H. Er. (2024) A botanical oasis rather than a biological desert: Rediscoveries, new species and new records in a tropical city. Plants, People, Planet 6: [697–709](https://nph.onlinelibrary.wiley.com/doi/full/10.1002/ppp3.10482).
1. Chisholm, R., N.P. Kristensen, F.E. Rheindt, **K.Y. Chong**, J.S. Ascher, K.K.P. Lim, P.K.L. Ng, D.C.J. Yeo, R. Meier, H.H. Tan, X. Giam, Y.S. Yeoh, W.W. Seah, L.M. Berman, H.Z. Tan, K.R. Sadanandan, M. Theng, W.F.A. Jusoh, A. Jain, B. Huertas, D.J.X. Tan, A.C.R. Ng, A. Teo, Y. Zeng, T.J.Y. Cho, Y.C.K. Sin. (2024) Two centuries of biodiversity discovery and loss in Singapore. Proceedings of the National Academy of Sciences 120: [e2309034120](https://www.pnas.org/doi/10.1073/pnas.2309034120).
1. Yuti Ariani Fatimah, Zaenuddin Hudi Prasojo, S.W. Smith, Nur Estya Binte Rahman, D.A. Wardle, **K.Y. Chong**, Asmadi Saad, J.S.H. Lee. (2023) Multi-level actor-network: Case of Peatland programs in a Riau Village, Indonesia (1974–2020). Geoforum 145: [103829](https://www.sciencedirect.com/science/article/pii/S0016718523001550).
1. Rahman, N.E.B., S.W. Smith, W.N. Lam, **K.Y. Chong**, M.S.E. Chua, P.Y. Teo, D.W.J. Lee, S.Y. Phua, C.Y. Aw, J.S.H. Lee, D.A. Wardle. (2023) Leaf decomposition and flammability are largely decoupled across species in a tropical swamp forest despite sharing some predictive leaf functional traits. New Phytologist 238: [598–611](https://nph.onlinelibrary.wiley.com/doi/10.1111/nph.18742).
1. Chiu, J.H., **K.Y. Chong**, S.K.Y. Lum, D.A. Wardle. (2023) Trends in the direction of global plant invasion biology research over the past two decades. Ecology & Evolution 13: [e9690](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.9690).
1. Lim, V.C., K.-W. Sing, **K.Y. Chong**, N. Jaturas, H. Dong, P.-S. Lee, T.T. Nguyen, T.L. Dzung, T. Bonebrake, T.P.N. Tsang, L. Chu, G.-J. Brandon-Mong, W.-L. Kong, M. Soga, J.-J. Wilson. (2022) Familiarity with, perceptions of, and attitudes towards, butterflies in urban parks in megacities across East and Southeast Asia. Royal Society Open Science 9: [220161](https://royalsocietypublishing.org/doi/10.1098/rsos.220161).
<a name="LamEtAl_2022"></a>
1. Smith, S.W., N.E.B. Rahman, M.E. Harrison, S. Shiodera, W. Giesen, M. Lampela, D.A. Wardle, **K.Y. Chong**, R. Agusti, L.S. Wijedasa, P.Y. Teo, Y.A. Fatimah, N.T. Teng, Y.K.Q. Joanne, M.J. Alam, P.B. Sintes, T. Darusman, Y. Ermiasi, L.L.B. Graham, D.R. Katoppo, K. Kojima, K. Kusin, D.P. Lestari, F. Metali, H.C. Morrogh-Bernard, M.B. Nahor, R.R.P. Napitupulu, D. Nasir, T.K. Nath, R. Nilus, M. Norisada, D. Rachmanadi, H.H. Rachmat, B.R. Capilla, Salahuddin, P.B. Santosa, R.S. Sukri, B. Tay, W. Tuah, T. Yamanoshita, Y. Yokoyama, T.W. Yuwati, J.S.H. Lee. (2022) Tree species that ‘live slow, die old’ enhance tropical peat swamp restoration: Evidence from a systematic review. Journal of Applied Ecology 59: [1950–1966](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.14232).
<a name="SimEtAl_2022"></a>
1. \*Lam, W.N., P.J. Chan, Y.Y. Ting, H.J. Sim, J.J. Lian, R. Chong, Nur Estya Rahman, L.W.A. Tan, Q.Y. Ho, Z. Chiam, Srishti Arora, Sorain J. Ramchunder, K.S.-H. Peh, Y. Cai, **K.Y. Chong**. (2022) Habitat specialization mediates the influence of leaf traits on canopy productivity. Ecosystems 25: [1006–1019](https://link.springer.com/article/10.1007/s10021-021-00697-7). [[pdf](https://www.dropbox.com/scl/fi/pfzt1lozsbufmu32nw3q6/lam-et-al-2022-habitat-adaptation-mediates-the-influence-of-leaf-traits-on-canopy-productivity-from-a-tropical-freshwater-swamp-forest.pdf?rlkey=7bfvysjelq4i5mbd41xntf5dm&dl=0)]
1. Sim, H.J., W.N. Lam, R.A. Chisholm, **K.Y. Chong**. (2022) Downstream resource leakage a necessary condition for the Stress-Gradient Hypothesis in processing chain commensalisms. Journal of Theoretical Biology 538: [111043](https://www.sciencedirect.com/science/article/abs/pii/S0022519322000418) [[pdf](https://www.dropbox.com/scl/fi/ie6vx29jnzfwwozddzbap/sim-et-al-2022-downstream-resource-leakage-a-necessary-condition-for-the-stress-gradient-hypothesis-in-processing-chain-commensalisms.pdf?rlkey=tbpek3tmcqz1b5dw8z64o8fuw&dl=0)].
<a name="ChongEtAl_2021"></a>
1. Lai, H.R., **K.Y. Chong**, A.T.K. Yee, M.M. Mayfield, D.B. Stouffer (2022) Non-additive biotic interactions improve predictions of tropical tree growth and impact community size structure. Ecology 103: [e03588](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.3588). [[pdf](https://www.dropbox.com/scl/fi/quj9gvgi86iuwdyffkg21/lai-et-al-2022-non-additive-biotic-interactions-improve-predictions-of-tropical-tree-growth-and-impact-community-size-structure.pdf?rlkey=zedpk7324e14ipoh66pzie7rv&dl=0)]
1. Song, X.P., **K.Y. Chong**. (2021) home2park : An R package to assess the spatial provision of urban parks. Journal of Open Source Software 6(65): [3609](https://joss.theoj.org/papers/10.21105/joss.03609).
1. \***Chong, K.Y.**, S.M.X. Hung, C.Y. Koh, R.C.J. Lim, J.W. Loh, L Neo, W.W. Seah, S.Y. Tan, H.T.W. Tan. (2021) Waterlogging and soil but not seedling competition structure tree communities in a catchment containing a tropical freshwater swamp forest. Journal of Vegetation Science 32: [e13072](https://onlinelibrary.wiley.com/doi/abs/10.1111/jvs.13072). [[pdf](https://www.dropbox.com/scl/fi/136suh4nbeznwnfk0kypf/chong-et-al-2021-waterlogging-and-soil-but-not-seedling-competition-structure-tree-communities-in-a-catchment-containing-a-tropical-freshwater-swamp-forest.pdf?rlkey=98uo2obq1p8yci9h0kg3ekw84&dl=0)]
<a name="LamEtAl_2021"></a>
1. \***Chong, K.Y.**, R.T. Corlett, M. Nuñez, K. Andersen, F. Courchamp, S.C. Chua, W. Dawson, S. Fei, S. Kuebbing, B.P.H. Lee, A Liebhold, S.K.Y. Lum, M. Luskin, K.M. Ngo, M. Padmanaba, L. Souza, D. Wardle. (2021) Are biological invasions different in the tropics? Annual Reviews in Ecology, Evolution & Systematics 52: [291–314](https://www.annualreviews.org/content/journals/10.1146/annurev-ecolsys-012021-095454). [[pdf](https://www.dropbox.com/scl/fi/s0lhyii2imdlv9ocu452i/chong-et-al-2021-are-terrestrial-biological-invasions-different-in-the-tropics.pdf?rlkey=b81ns6q9f6li2ls1t6m1ph7sl&dl=0)]
1. \*Lam, W.N., J.J. Lian, P.J. Chan, Y.Y. Ting, R. Chong, Nur Estya Rahman, L.W.A. Tan, Q.Y. Ho, Sorain J. Ramchunder, K.S.-H. Peh, Y. Cai, **K.Y. Chong**. (2021) Leaf litter decomposition in tropical freshwater swamp forests is slower in swamp than non-swamp conditions. Biotropica 53: [920–929](https://onlinelibrary.wiley.com/doi/abs/10.1111/btp.12913). [[pdf](https://www.dropbox.com/scl/fi/lx6vea9o4x0v14z95h56h/lam-et-al-2021-leaf-litter-decomposition-in-tropical-freshwater-swamp-forests-is-slower-in-swamp-than-non-swamp-conditions.pdf?rlkey=8k8oetxl4ygwfpwqf7r6b4kj5&dl=0)] [see also [GitHub repo](https://github.com/kwekings/NSSF3_litter_decomp)]
<a name="LaiEtAl_2021"></a>
1. Teo, H.C., Y. Zeng, T.V. Sarira, T.K. Fung, Q. Zheng, X.P. Song, **K.Y. Chong**, L.P. Koh. (2021) Global urban reforestation can be an important natural climate solution. Environmental Research Letters 16: [034059](https://iopscience.iop.org/article/10.1088/1748-9326/abe783).
<a name="ChongEtAl_2021"></a>
1. \*Lai, H.R., G.S.Y. Tan, L. Neo, C.Y. Kee, A.T.K. Yee, H.T.W. Tan, **K.Y. Chong** (2021) Decoupled responses of native and exotic tree diversities to distance from old-growth forest and soil phosphorous in post-cultivation secondary forests. Applied Vegetation Science 24: [e12548](https://onlinelibrary.wiley.com/doi/abs/10.1111/avsc.12548). [[pdf](https://www.dropbox.com/scl/fi/jdhltdwlod0ehikiz9424/lai-et-al-2021-decoupled-responses-of-native-and-exotic-tree-diversities-to-distance-from-old-growth-forest-and-soil-phosphorous-in-novel-secondary-forests.pdf?rlkey=n6ftucf3yvdjne0onc2xb2mh2&dl=0)] [see also [novelforestSG R package](https://hrlai.github.io/novelforestSG/)]
1. \***Chong, K.Y.**, Ng, W.Q., A.T.K. Yee, D.L. Yong. (2021) The community structure of bird assemblages on urban strangler figs. Biotropica 53: [255–265](https://onlinelibrary.wiley.com/doi/10.1111/btp.12866). [[pdf](https://www.dropbox.com/scl/fi/4nhksksh7cpl0g1hnomsz/chong-et-al-2021-the-community-structure-of-bird-assemblages-on-urban-strangler-figs.pdf?rlkey=nm83al57bofpq34t4q0al6wrs&dl=0)] [see also [GitHub repo](https://github.com/kwekings/UrbanFig)]
1. Kristensen, N., W.W. Seah, **K.Y. Chong**, Y.S. Yeoh, T. Fung, L. Berman, H.Z. Tan, R. Chisholm. (2020) Extinction rate of discovered and undiscovered plants in Singapore. Conservation Biology 34: [1229–1240](https://conbio.onlinelibrary.wiley.com/doi/abs/10.1111/cobi.13499).
1. Zeng, Y., T.V. Sarira, L.R. Carrasco, **K.Y. Chong**, D.A. Friess, J.S.H. Lee, P. Taillardat, T.A. Worthington, Y. Zhang, L.P. Koh. (2020) Economic and social constraints on reforestation for climate mitigation in Southeast Asia. Nature Climate Change 10: [842–844](https://www.nature.com/articles/s41558-020-0856-3).
1. Lai, H.R., **K.Y. Chong**, A.T.K. Yee, H.T.W. Tan, M. van Breugel. (2020) Functional traits that moderate tropical plant recruitment during post-windstorm secondary succession. Journal of Ecology 108: [1322–1333](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2745.13347). [[pdf](https://www.dropbox.com/scl/fi/g8wvzzs5qjhcg2ed19hir/lai-et-al-in-press-functional-traits-that-moderate-tropical-tree-recruitment-during-post-wind-storm-secondary-succession.pdf?rlkey=yyc4elaw3s7o9umzoq3xq67lh&dl=0)]
<a name="YeeEtAl_2019"></a>
1. \***Chong, K.Y.**, S. Teo, B. Kurukulasuriya, Y.F. Chung, X. Giam, H.T.W. Tan. (2019) The effects of landscape scale on greenery and traffic relationships with urban birds and butterflies. Urban Ecosystems 22: [917–926](https://link.springer.com/article/10.1007/s11252-019-00871-9). [[pdf](https://www.dropbox.com/scl/fi/kizr6ao2tqq99q9cz400k/chong-et-al-2019-the-effects-of-landscape-scale-on-greenery-and-traffic-relationshpis-with-urban-birds-and-butterflies.pdf?rlkey=tzfuu6wghhrg6sv4j9q37lu5i&dl=0)]
1. \*Yee, A.T.K., H.R. Lai, **K.Y. Chong**, L. Neo, C.Y. Koh, S.Y. Tan, W.W. Seah, J.W. Loh, R.C.J. Lim, M. van Breugel, H.T.W. Tan. (2019) Short-term responses in a secondary tropical forest after a severe windstorm event. Journal of Vegetation Science 30: [720–731](https://onlinelibrary.wiley.com/doi/abs/10.1111/jvs.12753). [[pdf](https://www.dropbox.com/scl/fi/aaw7ot7msxqw5gi8qrzc7/yee-et-al-2019-short-term-responses-in-a-secondary-tropical-forest-after-a-severe-windstorm-event.pdf?rlkey=an82oadsit2ickihvtbv7dlmv&dl=0)]
1. Coleman, J.L., J.S. Ascher, D. Bickford, D. Buchori, A. Cabanban, R.A. Chisholm, **K.Y. Chong**, P. Christie, G.R. Clements, T.E.E. dela Cruz, W. Dressler, D.P. Edwards, C.M. Francis, D.A. Friess, X. Giam, L. Gibson, D. Huang, A.C. Hughes, Z. Jaafar, A. Jain, L.P. Koh, E.P. Kudavidanage, B.P.Y.-H. Lee, J. Lee, T.M. Lee, M. Leggett, B. Leimona, M. Linkie, M. Luskin, A. Lynam, E. Meijaard, V. Nijman, A. Olsson, S. Page, P. Parolin, K.S.-H. Peh, M.R. Posa, G.W. Prescott, S.A. Rahman, S.J. Ramchunder, M. Rao, J. Reed, D.R. Richards, E.M. Slade, R. Steinmetz, P.Y. Tan, D. Taylor, P.A. Todd, S.T. Vo, E.L. Webb, A.D. Ziegler, L.R. Carrasco. (2019) Top 100 research questions for biodiversity conservation in Southeast Asia. Biological Conservation 234: [211–220](https://www.sciencedirect.com/science/article/abs/pii/S0006320718315751).
1. Lam, W.N., **K.Y. Chong**, G.S. Anand, H.T.W. Tan. (2019) In situ proteolytic activity in _Nepenthes gracilis_ pitcher plant traps is affected by both pitcher-extrinsic and pitcher-intrinsic factors. International Journal of Plant Sciences 180: [179–185](https://www.journals.uchicago.edu/doi/10.1086/700969).
1. Lam, W.N., W.Y. Wang, L.F. Cheong, J.K.H. Koh, M. Foo, **K.Y. Chong**, H.T.W. Tan. (2018) Pitcher plant facilitates prey capture in a sympatric congener. Plant Ecology 219: [299–311](https://link.springer.com/article/10.1007/s11258-018-0796-4).
1. Neo, L., **K.Y. Chong**, C.Y. Koh, S.Y. Tan, J.W. Loh, R.C.J. Lim, W.W. Seah, H.T.W. Tan. (2017) Borehole closure and the effects of increment coring on the health of some tropical trees, one year after coring. Journal of Tropical Forest Science 29: [519–529](https://www.frim.gov.my/v1/jtfsonline/jtfs/v29n4/519-529.pdf).
<a name="NeoEtAl_2017"></a>
1. Harrison, R.D., **K.Y. Chong**, C.K. Yeo, N.M. Pham, A.T.K. Yee, H.T.W. Tan, J.-Y. Rasplus. (2017) Pollination of _Ficus elastica_: Indian rubber re-establishes sexual reproduction in Singapore. Scientific Reports 7: [11616](https://www.nature.com/articles/s41598-017-09873-z).
<a name="ChongEtAl_2017"></a>
1. \*Neo, L., A.T.K. Yee, **K.Y. Chong**, C.Y. Kee, H.T.W. Tan. (2017) Vascular plant species richness and composition in two types of post-cultivation tropical secondary forest. Applied Vegetation Science 20: [692–701](https://onlinelibrary.wiley.com/doi/abs/10.1111/avsc.12322). [[pdf](https://www.dropbox.com/scl/fi/i6mw8jnfzsiv54lg88lap/neo-et-al-2017-vascular-plant-species-richness-and-composition-in-two-types-of-post-cultivation-tropical-secondary-forest.pdf?rlkey=fvovwmukbx7u435h4j4pun2p9&dl=0)] [see also [novelforestSG R package](https://hrlai.github.io/novelforestSG/)]
<a name="LamEtAl_2017"></a>
1. \***Chong, K.Y.**, M.B. Raphael, L.R. Carrasco, A.T.K. Yee, X. Giam, V.B. Yap, H.T.W. Tan. (2017) Reconstructing the invasion history of a spreading, non-native, tropical tree through a snapshot of current distribution, sizes, and growth rates. Plant Ecology 218: [673–685](https://link.springer.com/article/10.1007/s11258-017-0720-3). [[pdf](https://www.dropbox.com/scl/fi/08u1fxo7j1exa9gt31x53/chong-et-al-2017-reconstructing-the-invasion-history-of-a-spreading-non-native-tropical-tree-through-a-snapshot-of-current-distribution-sizes-and-growth-rates.pdf?rlkey=aexxjvy3tw916or0pzqcm2931&dl=0)]
<a name="ChongEtAl_2016"></a>
1. Lam, W.N., **K.Y. Chong**, G.S. Anand, H.T.W. Tan. (2017) Dipteran larvae and microbes facilitate nutrient sequestration in the _Nepenthes gracilis_ pitcher plant host. Biology Letters 13: [20160928](https://royalsocietypublishing.org/doi/10.1098/rsbl.2016.0928).
1. \***Chong, K.Y.**, R. Chong, L.W.A. Tan, A.T.K. Yee, M.A.H. Chua, K.M. Wong, H.T.W. Tan. (2016) Fruit fall, pre- and post-dispersal predation, and seedling survival of two _Shorea_ and two _Diperocarpus_ spp. in severely fragmented forests in Singapore. Plant Ecology & Diversity 9: [483–490](https://www.tandfonline.com/doi/abs/10.1080/17550874.2016.1266404). [[pdf](https://www.dropbox.com/scl/fi/wp2gf3c2i5031rr6q4mlu/chong-et-al-in-press-Seed-production-and-survival-of-four-dipterocarp-species-in-degraded-forests-in-Singapore.pdf?rlkey=d4clha6qytgmk5l0hfurrzwbh&dl=0)]
1. Yee, A.T.K., **K.Y. Chong**, L. Neo, H.T.W. Tan. (2016) Updating the classification system for the secondary forests of Singapore. Raffles Bulletin of Zoology Supplement 32: [11–21](https://lkcnhm.nus.edu.sg/app/uploads/2017/06/S32rbz011-021.pdf).
<a name="ZengEtAl_2015"></a>
1. Giam, X., R. Hidiaty, H.H. Tan, L. Parenti, D. Worwor, S. Sauri, **K.Y. Chong**, D. Yeo, D. Wilcove. (2015) Mitigating the impact of oil-palm monoculture on freshwater fishes in Southeast Asia. Conservation Biology 29: [1357–1367](https://conbio.onlinelibrary.wiley.com/doi/abs/10.1111/cobi.12483).
<a name="RaphaelEtAl_2015"></a>
1. Zeng, Y., **K.Y. Chong**, E.K. Grey, D.M. Lodge, D.C.J. Yeo. (2015) Disregarding human pre-introduction selection can confound invasive crayfish risk assessments. Biological Invasions 17: [2373–2385](https://link.springer.com/article/10.1007/s10530-015-0881-8).
1. \*Raphael, M.B., **K.Y. Chong**, V.B. Yap, H.T.W. Tan. (2015) Comparing germination rates and seedling traits between native and exotic pioneers: _Cecropia pachystachya_ versus _Macaranga gigantea_. Plant Ecology 216: [1019–1027](https://link.springer.com/article/10.1007/s11258-015-0486-4). [[pdf](https://www.dropbox.com/scl/fi/1fnx5p7smzdh3jq5mbjzn/raphael-et-al-2015-comparing-germination-success-and-seedling-traits-between-exotic-and-native-pioneers-cecropia-pachystachya-versus-macaranga-gigantea.pdf?rlkey=0ds0jhe81x837779px7qeynhz&dl=0)]
<a name="YeoEtAl_2014"></a>
1. \***Chong, K.Y.**, S. Teo, B. Kurukulasuriya, Y.F. Chung, S. Rajathurai, H.T.W. Tan. (2014) Not all green is as good: different effects of the spontaneous and cultivated components of urban vegetation on bird and butterfly diversity. Biological Conservation 171: [299–309](https://www.sciencedirect.com/science/article/abs/pii/S0006320714000494). [[pdf](https://www.dropbox.com/scl/fi/wgkn19qnlmp0ybhdnb7x5/chong-et-al-2014-not-all-green-is-as-good-different-effects-of-the-natural-and-cultivated-components-of-urban-vegetation-on-bird-and-butterfly-diversity.pdf?rlkey=8b2nfpvk181sucmzn37w2kh5g&dl=0)]
1. \*Yeo, H.H.T., **K.Y. Chong**, A.T.K. Yee, X. Giam, R.T. Corlett, H.T.W. Tan. (2014) Leaf litter depth as an important factor inhibiting seedling establishment of an exotic palm in tropical secondary forest patches. Biological Invasions 16: [381–392](https://link.springer.com/article/10.1007/s10530-013-0527-7). [[pdf](https://www.dropbox.com/scl/fi/oal0ag56yikot275kid3i/yeo-et-al-2014-leaf-litter-as-a-key-factor-inhibiting-seedling-establishment-of-an-invasive-palm-in-tropical-secondary-forest-patches.pdf?rlkey=f05rxkh9nylhbpyt14szlzphv&dl=0)] [see also [GitHub repo](https://github.com/kwekings/FYP_HazelinaYeo)]
1. \***Chong, K.Y.**, S.M.L. Lee, A.T. Gwee, P.K.F. Leong, S. Ahmad, W.F. Ang, A.F.S.L. Lok, C.K. Yeo, R.T. Corlett, H.T.W. Tan. (2012) Herbarium records do not predict rediscovery of presumed nationally extinct species. Biodiversity and Conservation 21: [2589–2599](https://link.springer.com/article/10.1007/s10531-012-0319-x). [[pdf](https://www.dropbox.com/scl/fi/l9d5un2ozidevepo2l9v0/chong-et-al-2012-herbarium-records-do-not-predict-rediscovery-of-presumed-nationally-extinct-species.pdf?rlkey=x5m4sxz4d727dcztfq9tavur3&dl=0)]
1. \***Chong, K.Y.**, S. Teo, B. Kurukulasuriya, Y.F. Chung, S. Rajathurai, H.C. Lim, H.T.W. Tan. (2012) Decadal changes in urban bird abundance in Singapore. Raffles Bulletin of Zoology Supplement 25: [181¬–188](https://lkcnhm.nus.edu.sg/app/uploads/2017/06/s25rbz189-196.pdf).
1. Giam X., G.R. Clements, S.A. Aziz, **K.Y. Chong**, J. Miettinen. (2011) Rethinking the back to wilderness concept for Sundaland’s forests. Biological Conservation 144: [3149–3152](https://www.sciencedirect.com/science/article/abs/pii/S0006320711003673).
1. \***Chong, K.Y.**, R.T. Corlett, D.C.J. Yeo, H.T.W. Tan. (2011) Towards a global database of weed risk assessments: a test of transferability for the tropics. Biological Invasions 13: [1571-1577](https://link.springer.com/article/10.1007/s10530-010-9914-5). [[pdf](https://www.dropbox.com/scl/fi/1gwyecydh6iobgvctwsjz/chong-et-al-2011-towards-a-global-database-of-weed-risk-assessments-a-test-of-transferability-for-the-tropics.pdf?rlkey=pda5177dvt9po8r8ic9qodkeo&dl=0)]
1. Todd, P.A., W. Qiu, **K.Y. Chong**. (2009) Ontogenetic shifts in carapace patterning and/or colouration in interdital and subtidal brachyuran crabs. Raffles Bulletin of Zoology 57(2): 543-550.


# B. Books & book chapters

1. Middleton, D.J., S. Lindsay, B.C. Ho, **K.Y. Chong**, P. Athen, Bazilah Ibrahim, J. Chen, L.M.J. Chen, L.M. Choo, J.W.M. Gan, S.K. Ganesan, E.M. Gardner, A.Q. Hu, S.L. Koh, H. Kurzweil, S. Lai, W.N. Lam, S.M.L. Lee, P.K.F. Leong, J. Leong-Škorničková, D.C.H. Liew, R.C.J. Lim, W.H. Lim, Y.W. Low, H.K. Lua, L. Neo, X.Y. Ng, M.A. Niissalo, A. Phang, M.L. Rodda, W.W. Seah, D.C. Thomas, I.M. Turner, K.M. Wong, S.M. Yaakub, C.K. Yeo, Y.S. Yeoh. (2024) Flora / Checklist of Flora species with their category of threat status for Singapore. In: Davison, G.W.H., J.W.M. Gan, D. Huang, W.S. Hwang, S.K.Y. Lum, D.C.J. Yeo (eds.) [The Singapore Red Data Book: Red lists of Singapore Biodiversity, 3rd edition](https://www.nparks.gov.sg/-/media/biodiversity/nparks-rdb3-checklists-ecopy-21-may2024.pdf). National Parks Board, Singapore. Pp. 23 – 60 / 454–514.
1. **Chong, K.Y.** (2023) From plant-blind to botanist. In: T. Koh, L.H. Lye, S. Lum (eds.) Peace with Nature. [Pp. 33–38](https://www.worldscientific.com/doi/abs/10.1142/9789811282027_0005).
1. Ganesan, S.K., **K.Y. Chong**, Lim R.C.J., Lua H.K., Ng X.Y., Elango Velautham. (2023) Dipterocarpaceae in Singapore. In: Khoo, E., M. Barstow, C. Maycock, V. Bodos, K.Y. Chong, L.S.L. Chua, D. Cicuzza, S. Deepu, A. Dhyani, A.N. Divina, G.T. Eduarte, V.M. Evangelista, S.K. Ganesan, R.C. Gibe, N. Gunatilleke, S.Gunatillke , Z. Haji Berudin, A. Hamidi, P.K Hoo, T. Jimbo, S. Juiling, Y.W.C. Kusuma, Y. Kusumadewi, C.Y. Ling, R.C.J. Lim, H.K. Lua, J.M.P. Magbuo, P.L. Malabrigo Jr., R. Majapun, A. Maryani A.M., X.Y. Ng, R. Nilus, J.T. Pereira, J. Sang, H.H. Rachmat, S. Ranasinghe, A. Randi, I. Robiansyah, J.S. Solatre, J.S. Strijk, J.B. Sugua, JW. Tang, S. Tanggaraju, M.M.B. Tating, A.B. Tobias, S. Tsen, A.G.A. Umali, E. Velautham, YX. Xiao, W. Yong, WB. Yu. [The Red List of Dipterocarpaceae](https://www.bgci.org/wp/wp-content/uploads/2023/03/RLDipterocarpaceaeMedResReduced.pdf). Botanic Gardens Conservation International. Pp. 55–56.
<a name="gazetteer2014"></a>
1. Yee, A.T.K., **K.Y. Chong**, W.W. Seah, H.K. Lua., S. Yang. (2019) Vegetation of Singapore. In: Middleton et al. (eds.) Flora of Singapore, Vol. 1. National Parks Board, Singapore. [Pp. 47–70](https://www.nparks.gov.sg/-/media/sbg/flora-of-singapore/volume-1-introduction/1,-d-,5_vegetation_lr.pdf).
1. Chen, J., **K.Y. Chong**, A.T.K. Yee, H.T.W. Tan. (2014) [A Gazetteer of the Singapore Locality Names of the Collections of the Herbarium, Singapore Botanic Gardens](https://lkcnhm.nus.edu.sg/app/uploads/2017/04/gazetteer_locality_names.pdf). Lee Kong Chian Natural History Museum, National University of Singapore. 68 pp.
1. **Chong, K.Y.**, M.A.H. Chua, M.L. Neo, D.J.J. Ng, S.M. Yaakub, T.C. Toh, A.K.S. Wee, D.L. Yong. (2014) Impacts of development on biodiversity in Singapore. In: J. Appleton (ed.) Values in Sustainable Development. Routledge. [Pp. 286–298](https://www.taylorfrancis.com/chapters/edit/10.4324/9780203080177-32/impact-development-biodiversity-singapore-kwek-yan-chong-marcus-aik-hwee-chua-mei-lin-neo-daniel-jia-jun-ng-siti-maryam-yaakub-tai-chong-toh-alison-kim-shan-wee-ding-li-yong).
<a name="ErEtAl_2023"></a>
1. **Chong, K.Y.**, H.T.W. Tan, R.T. Corlett. (2009) [A Checklist of the Total Vascular Plant Flora of Singapore: Native, Naturalised and Cultivated Species](https://lkcnhm.nus.edu.sg/app/uploads/2017/04/flora_of_singapore_tc.pdf). Raffles Museum of Biodiversity Research, National University of Singapore. 273 pp.


# C. Other peer-reviewed articles

<!---
Nur Estya Binte Rahman, Y.Y. Ting, R. Chong, Q.Y. Ho, L.W.A. Tan, Z. Chiam, **K.Y. Chong**. (in preparation) The vascular plant flora of Springleaf Forest.
Ting, Y.Y., R.C.J. Lim, W.N. Lam, P.J. Chan, S.K. Ganesan, **K.Y. Chong**. (in preparation) Towards a field guide to the trees of the Nee Soon Catchment (X): Malvaceae.
Loh, J.W., **K.Y. Chong**, Neo L., S.Y. Tan, C.Y. Koh, R.C.J. Lim, W.Q. Ng, W.W. Seah, A.T.K. Yee, H.T.W. Tan. (in preparation) Towards a field guide to the trees of the Nee Soon Catchment (IX): Elaeocarpus (Elaeocarpaceae).
--->
1. Er, K.B.H., **K.Y. Chong**, T.Y.S. Choo, D.J. Middleton, P.Y. Tan. (2023) Establishing a network of long-term forest monitoring plots in Singapore. Gardens’ Bulletin Singapore 75: [1–20](https://www.nparks.gov.sg/sbg/research/publications/gardens'-bulletin-singapore/-/media/sbg/gardens-bulletin/gbs_75_01_y2023/75_01_01_y2023_v7501_gbs_pg1.ashx).
1. Chan, P.J., Parusuraman Athen, X.Y. Ng, **K.Y. Chong**. (2023) Biodiversity Record: _Litsea ferruginea_ in the Central Catchment Nature Reserve. Nature in Singapore 16: [e2023049](https://lkcnhm.nus.edu.sg/wp-content/uploads/sites/10/2023/05/NIS-2023-0049.pdf).
1. Ali Ibrahim, R. Chong, S.Y. Soh, Muhammad Khairuldin Aziz, P.Y.L. Tan, J.S.Y. Tan, **K.Y. Chong**. (2023) Biodiversity Record: Rediscovery of _Engelhardia serrata_ in Singapore. Nature in Singapore 16: [e2023047](https://lkcnhm.nus.edu.sg/wp-content/uploads/sites/10/2023/05/NIS-2023-0047.pdf).
<a name="HughTanSpecial_LaiEtAl"></a>
1. Sim, D.Z.H., M.A.D. Mowe, **K.Y. Chong**, D.C.J. Yeo. (2022) An overview and checklist of non-native and cryptogenic vascular macrophytes in Singapore’s fresh waters. Nature in Singapore Supplement 1: [e2022120](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/03/NIS_S1_190-206.pdf).
1. Lai, H.R., **K.Y. Chong**, A.T.K. Yee. (2022) Ten years after: what we learned from the Mandai storm forest. Nature in Singapore Supplement 1: [e2022121](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/03/NIS_S1_207-218.pdf).
1. Er, K.B.H., **K.Y. Chong**, W.F. Ang, X.Y. Ng, A.H.B. Loo (2022) Three decades of floristic inventory, description and recovery efforts in Singapore. Nature in Singapore Supplement 1: [e2022067](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/03/NIS_S1_1-9.pdf).
1. Lindsay, S., D.J. Middleton, B.C. Ho, **K.Y. Chong**, I.M. Turner, Ali Ibrahim, M. Alonso-García, W.F. Ang, P.S. Ashton, P. Athen, S. Atkins, Bazilah Ibrahim, H.J. Beentje, C.M. Boo, P.C. Boyce, G.L.C. Bramley, S. Buerki, M.W. Callmander, S. Chantanaorrapint, M. Cheek, C.-W. Chen, J. Chen, L.M.J. Chen, P.T. Chew, R. Chong, L.M. Choo, R.C.K. Chung, M.J.E. Coode, S.C. Chua, D. Cicuzza, R.P.J. de Kok, G.W.H. Davison, W.J.J.O. de Wilde, H. Duistermaat, A. Dubéarnès, B.E.E. Duyfjes, L.T. Ellis, H.-J. Esser, P.R. Gajurel, S.W. Gale, S.K. Ganesan, E.M. Gardner, D.L. Geiger, R.K. Harwood, Hassan Ibrahim, S. He, A. Henderson, P.H. Hovenkamp, M. Hughes, Zaki Jamil, M.H.P. Jebb, D.M. Johnson, A. Kartonegoro, R. Kiew, S. Knapp, S.L. Koh, H. Kurzweil, S. Lee, P.K.F. Leong, J. Leong-Škorničková, G.A. Levin, D.C.H. Liew, R.C.J. Lim, W.H. Lim, A.H.B. Loo, Y.W. Low, H.K. Lua, S. Lum, D.J. Mabberley, R. Mahyuni, B. Maslin, N.A. Murray, L. Neo, X.Y. Ng, K.M. Ngo, M.A. Niissalo, P.T. Ong, C.M. Pannell, A. Phang, G.T. Prance, C. Promma, C. Puglisi, M.L. Rodda, S.C.K. Rubasinghe, R.M.K. Saunders, I.A. Savinov, L.G. Saw, A. Schuiteman, W.W. Seah, D.A. Simpson, J.S. Strijk, P. Sukkharak, M. Sugumaran, S. Syahida-Emiza, J.P.C. Tan, N.P. Taylor, Y.K.L. Teo, D.C. Thomas, A. Trias-Blasi, T. Utteridge, P.C. van Welzen, J.F. Veldkamp, J. Vermeulen, R. Wang, P. Wilkie, Y.-M. Wei, S.Y. Wong, K.M. Wong, S. Yaakub, T.M. Yam, S. Yang, T.L. Yao, W. Ye, A.T.K. Yee, C.K. Yeo, Y.S. Yeoh, C. Yong, K.T. Yong, N.J.C. Zerega, R.-L. Zhu, K.B.H. Er. (2022) Flora of Singapore: Checklist and bibliography. Gardens’ Bulletin Singapore 74 (Supplement 1): [3–860](https://www.nparks.gov.sg/sbg/research/publications/gardens'-bulletin-singapore/-/media/sbg/gardens-bulletin/gbs_74_s1_y2022/74_s1_01_y2022_v74s1_gbs_pg03.pdf).
1. Chan, P.J., W.N. Lam, Y.Y. Ting, R. Chong, Nur Estya Rahman, **K.Y. Chong**. (2022) Towards a field guide to the trees of the Nee Soon Catchment (VIII): Sapotaceae. Nature in Singapore Supplement 1: [e2022074](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/03/NIS_S1_129-158.pdf).
1. Lam, W.N., J.W. Loh, R. Chong, Y.Y. Ting, P.J. Chan, **K.Y. Chong**. (2022) Towards a field guide to the trees of the Nee Soon Catchment (VII): Phyllanthaceae. Nature in Singapore Supplement 1: [e2022073](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/03/NIS_S1_60-128.pdf).
1. Hung, S.M.X., W.W. Seah, **K.Y. Chong**. (2022) Towards a field guide to the trees of the Nee Soon Catchment (VI): _Calophyllum_ (Calophyllaceae). Nature in Singapore Supplement 1: [e2022072](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/03/NIS_S1_38-59.pdf).
1. Chan, P.J., Y.Y. Ting, Nur Estya Rahman, R. Chong, W.N. Lam, **K.Y. Chong**. (2020) _Acer laurinum_ (Sapindaceae), a new record for Singapore. Gardens’ Bulletin Singapore 72: [165–172](https://www.nparks.gov.sg/sbg/research/publications/gardens'-bulletin-singapore/-/media/sbg/gardens-bulletin/gbs_72_02_y2020/72_02_05_y2020_v7202_gbs_pg165.pdf).
1. Seah, W.W., S.M.X. Hung, **K.Y. Chong**. (2019) Flora of Singapore precursors, 17. Clarification of some names in the genus _Calophyllum_ as known in Singapore. Gardens’ Bulletin Singapore 71: [407–414](https://www.nparks.gov.sg/sbg/research/publications/gardens'-bulletin-singapore/-/media/sbg/gardens-bulletin/gbs_71_02_y2019/71_02_07_y2019_v71p2_gbs_pg407.pdf).
1. Seah, W.W., **K.Y. Chong**, Neo L., S.Y. Tan, C.Y. Koh, R.C.J. Lim, J.W. Loh, W.Q. Ng, A.T.K. Yee, H.T.W. Tan. (2019) Towards a field guide to the trees of the Nee Soon Catchment (V): Burseraceae. Nature in Singapore 12: [15–36](https://lkcnhm.nus.edu.sg/wp-content/uploads/sites/10/app/uploads/2019/05/NIS-2019-0004.pdf).
<a name="MarineParkI"></a>
1. **Chong, K.Y.**, R.C.J. Lim, J.W. Loh, L. Neo, W.W. Seah, S.Y. Tan, H.T.W. Tan (2018) Rediscoveries, new records and the floristic value of the Nee Soon Swamp Forest. Gardens’ Bulletin Singapore 70 (Supplement 1): [49–69](https://www.nparks.gov.sg/sbg/research/publications/gardens'-bulletin-singapore/-/media/sbg/gardens-bulletin/gbs_70_s1_y2018_v70_s1/70_s1_49_y2018_v70s1_gbs_pg49.pdf).
<a name="MarineParkII"></a>
1. Hung, S.M.X., **K.Y. Chong**, A.T.K. Yee, R.C.J. Lim, J.W. Loh, L. Neo, W.W. Seah, S.Y. Tan, H.T.W. Tan. (2017) The vascular plant flora and vegetation of the islands associated with Singapore’s first Marine Park (III): St. John’s Island. Nature in Singapore 10: [37–48](https://lkcnhm.nus.edu.sg/app/uploads/2017/06/2017nis037-048.pdf).
<a name="MarineParkIII"></a>
1. Hung, S.M.X., **K.Y. Chong**, A.T.K. Yee, R.C.J. Lim, J.W. Loh, L. Neo, W.W. Seah, S.Y. Tan, H.T.W. Tan. (2017) The vascular plant flora and vegetation of the islands associated with Singapore’s first Marine Park (II): Pulau Tekukor. Nature in Singapore 10: [25–35](https://lkcnhm.nus.edu.sg/app/uploads/2017/06/2017nis025-035.pdf).
1. Hung, S.M.X., **K.Y. Chong**, A.T.K. Yee, R.C.J. Lim, J.W. Loh, L. Neo, W.W. Seah, S.Y. Tan, A.X.Y. Teo, K. Tun, C.H.Y. Tong, K.S. Koh, H.T.W. Tan. (2017) The vascular plant flora and vegetation of the islands associated with Singapore’s first Marine Park (I): The Sisters’ Islands. Nature in Singapore 10: [7–24](https://lkcnhm.nus.edu.sg/wp-content/uploads/sites/11/app/uploads/2017/06/2017nis007-024.pdf).
1. Tan, S.Y., **K.Y. Chong**, Neo L., C.Y. Koh, R.C.J. Lim, J.W. Loh, W.Q. Ng, W.W. Seah, A.T.K. Yee, H.T.W. Tan. (2016) Towards a field guide to the trees of the Nee Soon Catchment (IV): _Xanthophyllum_ (Polygalaceae). Nature in Singapore 9: [139–147](https://lkcnhm.nus.edu.sg/app/uploads/2020/05/2016nis139-147_2.pdf).
1. Lim, R.C.J., **K.Y. Chong**, Neo L., S.Y. Tan, C.Y. Koh, J.W. Loh, W.Q. Ng, W.W. Seah, A.T.K. Yee, H.T.W. Tan. (2016) Towards a field guide to the trees of the Nee Soon Catchment (III): Myristicaceae. Nature in Singapore 9: [69–138](https://lkcnhm.nus.edu.sg/app/uploads/2017/04/2016nis069-138.pdf).
1. Neo, L., **K.Y. Chong**, S.Y. Tan, C.Y. Koh, R.C.J. Lim, J.W. Loh, W.Q. Ng, W.W. Seah, A.T.K. Yee, H.T.W. Tan. (2016) Towards a field guide to the trees of the Nee Soon Catchment (II): _Cratoxylum_ (Hypericaceae). Nature in Singapore 9:[29–39](https://lkcnhm.nus.edu.sg/wp-content/uploads/sites/10/app/uploads/2017/06/2016nis029-039.pdf).
1. **Chong, K.Y.**, L. Neo, S.Y. Tan, C.Y. Koh, R.C.J. Lim, J.W. Loh, W.Q. Ng, W.W. Seah, A.T.K. Yee, H.T.W. Tan. (2016) Towards a field guide to the trees of the Nee Soon Catchment (I): Lauraceae. Nature in Singapore 9: [1–28](https://lkcnhm.nus.edu.sg/app/uploads/2017/04/2016nis001-028.pdf).
<a name="WindsorForest"></a>
1. Chung, Y.F., S. Teo, **K.Y. Chong**, B.R. Kurukulasuriya, H.T.W. Tan. (2015) Weed risk assessment of the exotic species of _Plectranthus_ L’Hér. (Lamiaceae) in Singapore. Nature in Singapore 8: [1–13](https://lkcnhm.nus.edu.sg/app/uploads/2017/04/2015nis001-013.pdf).
<a name="UppThomsonForest"></a>
1. Neo, L., A.T.K. Yee, **K.Y. Chong**, H.T.W. Tan. (2014) The vascular plant flora of abandoned plantations in Singapore IV: Windsor Forest. Nature in Singapore 7: [93–109](https://lkcnhm.nus.edu.sg/app/uploads/2017/04/2014nis093-109.pdf).
<a name="BtBatok"></a>
1. Neo, L., A.T.K. Yee, **K.Y. Chong**, H.T.W. Tan. (2014) The vascular plant flora of Upper Thomson Forest. Nature in Singapore 7: [55–68](https://lkcnhm.nus.edu.sg/app/uploads/2017/04/2014nis055-068.pdf).
1. Neo, L., A.T.K. Yee, **K.Y. Chong**, C.Y. Kee, R.C.J. Lim, W.Q. Ng, X.Y. Ng, H.T.W. Tan. (2013) The vascular plant flora of Bukit Batok, Singapore. Nature in Singapore 6: [265–287](https://lkcnhm.nus.edu.sg/app/uploads/2017/06/2013nis265-287.pdf).
<a name="LentorForest"></a>
1. Lee, S.H., A.B.C. Ng, R.C.J. Lim, R. Francisco, W.Q. Ng, X.Y. Ng, L. Neo, A.T.K. Yee, **K.Y. Chong**, H.T.W. Tan. (2013) Status and Distribution in Singapore of _Ficus virens_ Aiton (Moraceae). Nature in Singapore 6: [223–227](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2013nis223-227.pdf).
<a name="DoverForest"></a>
1. Neo, L., A.T.K. Yee, **K.Y. Chong**, T.C. Zeng, H.T.W. Tan. (2013) The vascular plant flora of abandoned plantations in Singapore III: Lentor Forest. Nature in Singapore 6: [113–124](https://lkcnhm.nus.edu.sg/app/uploads/2017/04/2013nis113-124.pdf).
<a name="AdmiraltyForest"></a>
1. Neo, L., A.T.K. Yee, **K.Y. Chong**, H.H.T. Yeo, H.T.W. Tan. (2013) The vascular plant flora of Dover Forest, Singapore. Nature in Singapore 6: [73–83](https://lkcnhm.nus.edu.sg/app/uploads/2017/04/2013nis073-083.pdf).
1. Neo, L., A.T.K. Yee, **K.Y. Chong**, C.Y. Kee, H.T.W. Tan. (2013) The vascular plant flora of Admiralty Forest, Singapore. Nature in Singapore 6: [61–72](https://lkcnhm.nus.edu.sg/app/uploads/2017/06/2013nis061-072.pdf).
<a name="PunggolEndForest"></a>
1. Yeo, C.K., S.Y. Tan, C.Y. Koh, **K.Y. Chong**, X.Y. Ng, J.T.K. Lai. (2013) Leaf-cutting propagation of _Arthyrium accedens_ (Blume) Milde (Woodsiaceae). Nature in Singapore 6: [39–43](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2013nis039-043-5.pdf).
1. Neo, L., A.T.K. Yee, **K.Y. Chong**, H.H.T. Yeo, H.T.W. Tan. (2013) The vascular plant flora of abandoned plantations in Singapore II: Punggol End forest. Nature in Singapore 6: [7–17](https://lkcnhm.nus.edu.sg/app/uploads/2017/06/2013nis007-017-5.pdf).
<a name="ClementiForest"></a>
1. Yeo, C.K., X.Y. Ng, W.Q. Ng, **K.Y. Chong**, W.F. Ang, Ali bin Ibrahim. (2012) _Ficus stricta_ (Miq.) Miq.: a new record in Singapore. Nature in Singapore 5: [351–358](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2012nis351-358.pdf).
1. Neo, L., A.T.K. Yee, **K.Y. Chong**, H.T.W. Tan. (2012) The vascular plant flora of abandoned plantations in Singapore I: Clementi forest. Nature in Singapore 5: [275–283](https://lkcnhm.nus.edu.sg/app/uploads/2017/06/2012nis275-283.pdf).
1. Yeo, C.K., B.Y.Q. Ng, P.X. Ng, **K.Y. Chong**, A.F.S.L. Lok, W.F. Ang, S.Y. Tan, H.T.W. Tan. (2011) Air-layering: a suitable method for mass-propagating the nationally critically endangered _Fagraea auriculatum_ Jack (Gentianaceae). Nature in Singapore 4: [383–392](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2011nis383-392.pdf).
1. **Chong, K.Y.**, H.T.W. Tan, R.T. Corlett. (2011) A summary of the total vascular plant flora of Singapore. Gardens’ Bulletin Singapore 63: [197–204](https://www.nparks.gov.sg/sbg/research/publications/the-gardens'-bulletin-singapore/-/media/sbg/gardens-bulletin/gbs_63_01,-a-,02_y2011_v63_01,-a-,02/63_01,-a-,02_197_y2011_v63p1,-a-,p2_gbs_pg_197.pdf).
1. Ang, W.F., A.F.S.L. Lok, **K.Y. Chong**, C.K. Yeo, B.Y.Q. Ng, P.X. Ng, H.T.W. Tan. (2011) _Eulophia_ R. Br. ex Lindl. (Orchidaceae) of Singapore. Nature in Singapore 4: [289–296](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2011nis289-296.pdf).
1. Teo, S., R.K.H. Yeo, **K.Y. Chong**, Y.F. Chung, L. Neo, H.T.W. Tan. (2011) The flora of Pulau Semakau: a Project Semakau checklist. Nature in Singapore 4: [263–272](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2011nis263-272.pdf).
1. Teo, S., **K.Y. Chong**, B.R. Kurukulasuriya, Y.F. Chung, H.T.W. Tan. (2011) The status of an exotic shrub, _Acalypha siamensis_ Oliv. ex Gage (Euphorbiaceae), in Singapore. Nature in Singapore 4: [227–231](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2011nis227-231.pdf).
1. Teo, S., **K.Y. Chong**, Y.F. Chung, B.R. Kurukulasuriya, H.T.W. Tan. (2011) Casual establishment of some cultivated urban plants in Singapore. Nature in Singapore 4: [127–133](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2011nis127-133.pdf).
1. Lok, A.F.S.L., W.F. Ang, **K.Y. Chong**, C.K. Yeo, Hugh T.W. Tan. (2011) Rediscovery in Singapore of _Coelogyne rochussenii_ De Vriese (Orchidaceae). Nature in Singapore 4: [49–53](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2011nis049-053.pdf).
1. Lok, A.F.S.L., W.F. Ang, **K.Y. Chong**, P.X. Ng, S. Teo, A.T.K. Yee, C.K. Yeo, H.T.W. Tan. (2011) The status of _Caesalpinia bonduc_ (L.) Roxb. in Singapore. Nature in Singapore 4: [43–48](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2011nis043-048.pdf).
1. Ang, W.F., A.F.S.L. Lok, **K.Y. Chong**, H.T.W. Tan. (2010) Status and distribution of _Neoscortechinia sumatrensis_ S. Moore (Euphorbiaceae). Nature in Singapore 3: [333–336](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2010nis333-336.pdf).
1. Lok, A.F.S.L., W.F. Ang, **K.Y. Chong**, H.T.W. Tan. (2010) Rediscovery of _Liparis barbata_ Lindl. (Orchidaceae) in Singapore. Nature in Singapore 3: [277–281](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2010nis277-281.pdf).
1. Lok, A.F.S.L., K.-x. Tan, **K.Y. Chong**, L.T.P. Nghiem, H.T.W. Tan. (2010) The distribution and ecology of _Cecropia_ species (Urticaceae) in Singapore. Nature in Singapore 3: [199–209](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2010nis199-209.pdf).
1. Lok, A.F.S.L., **K.Y. Chong**, K.-x. Tan, H.T.W. Tan. (2010) A checklist of the spontaneous exotic vascular plant flora of Singapore. COSMOS 6: [57–83](https://www.worldscientific.com/doi/10.1142/S0219607710000474). [[pdf](https://www.dropbox.com/scl/fi/18e5d6vfq0nsmxyeivoh0/lok-et-al-2010-a-checklist-of-the-spontaneous-exotic-vascular-plant-flora-of-singapore.pdf?rlkey=fzo32f9w9ig3ggoimwc9vwekj&dl=0)]
1. **Chong, K.Y.**, P.X. Ng, H.T.W. Tan. (2010) Identity and status of a naturalising _Senna_ species in Singapore. Nature in Singapore 3: [171–174](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2010nis171-174.pdf).
1. Ang, W.F., A.F.S.L. Lok, **K.Y. Chong**, B.Y.Q. Ng, S.M. Suen, Hugh T.W. Tan. (2010) The distribution and status in Singapore of _Rubus molucannus_ L. var. _angulosus_ Kalkman (Rosaceae). Nature in Singapore 3: [91-97](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2010nis091-097.pdf).
1. **Chong, K.Y.**, P.T. Ang, H.T.W. Tan. (2010) Identity and spread of an exotic _Syngonium_ species in Singapore. Nature in Singapore 3: [1–5](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/02/2010nis1-5.pdf).


# D. Commentaries & other contributions

1. Muhammad Khairuldin bin Aziz, R. Chong, S.Y. Soh, **K.Y. Chong**. (2023) Forest research by the Singapore Botanic Gardens, from past to present. Gardenwise [61](https://www.nparks.gov.sg/sbg/research/publications/-/media/sbg/gardenwise/gw_pdf_2020-2029/gw_2023_vol_61_sept_v2.pdf): 20–25.
1. **Chong, K.Y.**, L. Neo, T.H. Ng. (2022) Preface: Singapore’s botanist, Associate Professor Hugh Tan. Nature in Singapore Supplement 1, [pp. iii–vi](https://www.science.nus.edu.sg/wp-content/uploads/sites/11/2024/03/NIS_S1_01_iii-vi_Preface.pdf). [Preface]
1. **Chong, K.Y.**, G. Khew, D. Middleton, D. Thomas, K.M. Wong. (2022) Nurturing the next generation of botanists. Gardenwise 59: 20–23.
1. Siman, K., D.A. Friess, M. Huxham, S. McGowan, J. Drewer, L.P. Koh, Y. Zeng, A.M. Lechner, J.S.H. Lee, C.D. Evans, S. Evers, A. J. Jovani-Sancho, H. Varkkey, G. Anshari, A. Jaya, **K.Y. Chong**, S. Page, S. Mishra, S. Sjögersten. (2021) Nature-based solutions for climate-change mitigation: challenges and opportunities for the ASEAN region. British High Commission and the COP26 Universities Network. 36 pp. [Policy Report]
1. **Chong, K.Y.**, X. Giam. (2016) Cross-Island Line issue highlights need for more debate on environmental decisions. TODAY Commentary. 4th March 2016. [Op-Ed]
1. Jain, A., **K.Y. Chong**, M.A.H. Chua, G.R. Clements. (2014) Moving away from paper corridors in Southeast Asia. Conservation Biology 28: 889–891. [Guest editorial]
1. Lee, J., A.G. Gosler, D. Vyas, J. Schaefer, **K.Y. Chong**, P. Kahumbu, S.M. Awoyemi, T. Baugh. (2013) Statement of the Society for Conservation Biology on the Use of Ivory for Religious Objects as Developed by the Religion and Conservation Research Collaborative of the Society’s Working Group on Religion and Conservation Biology.
1. Awoyemi, S.M., A.G. Gosler, I. Ho, J. Schaefer, **K.Y. Chong**. (2012) Mobilizing religion and conservation in Asia. Science 338: 1537–1538. [Letter to editor]
1. **Chong, K.Y.** (2012) Religiously protecting Myanmar’s environment. Science 337: 1604–1605. [Letter to editor]
1. Awoyemi S.M., J. Schaefer, A. Gosler, T. Baugh, **K.Y. Chong**, E. Landen. (2012) Society for Conservation Biology (SCB)’s Position on the Religious Practice of Releasing Captive Wildlife for Merit. Religion and Conservation Research Collaborative (RCRC) of the Religion and Conservation Biology Working Group (RCBWG).
1. **Chong, K.Y.** Where has all the flora gone? Straits Times Forum. 30th September 2011. [Letter to editor]
1. **Chong, K.Y.** Animal release: science, compassion and religion. Today Voices. 21st May 2011. [Letter to editor]
1. **Chong, K.Y.** Saving endangered species in Singapore: Let’s walk the talk. Straits Times Forum. 6th January 2011. [Letter to editor]
1. **Chong, K.Y.** Face up to the green fact. Straits Times Forum Online. 24th May 2010. [Letter to editor]
1. **Chong, K.Y.**, C.K. Yeo, A.T.K. Yee. (2010) Changing climate threatens tropical rainforests too. Nature 465: 420. [Letter to editor]
1. **Chong, K.Y.**, A.T.K. Yee, C.K. Yeo. (2010) Biodiversity: linking Singapore’s fragmented habitats. Nature 465: 289. [Letter to editor]